default_language_version:
  python: python3.11

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-toml
  - id: check-toml
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: forbid-new-submodules
  - id: mixed-line-ending
  - id: pretty-format-json
    args: [--autofix]
  - id: trailing-whitespace

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.8.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
    types_or: [yaml]
  - id: pretty-format-toml
    args: [--autofix]
    # types_or: [toml]
    exclude: |
      (?x)^(
      poetry\.lock |
      pyproject\.toml
      )$

- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.16
  hooks:
  - id: mdformat
    additional_dependencies:
    - mdformat-gfm
    - mdformat-black
    args: [--number]

- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.9.0.2
  hooks:
  - id: shellcheck

- repo: https://github.com/asottile/pyupgrade
  rev: v3.4.0
  hooks:
  - id: pyupgrade
    args: [--py311-plus, --keep-runtime-typing]

- repo: https://github.com/PyCQA/autoflake
  rev: v2.1.1
  hooks:
  - id: autoflake
    args: [--in-place, --remove-all-unused-import]

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
    args: [--profile, black]
    name: isort (python)
  - id: isort
    args: [--profile, black]
    name: isort (pyi)
    types: [pyi]


- repo: https://github.com/aio-libs/sort-all
  rev: v1.2.0
  hooks:
  - id: sort-all

- repo: https://github.com/ambv/black
  rev: 23.3.0
  hooks:
  - id: black

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.265   # Upgrade along with version in pyproject.toml dev dependencies
  hooks:
  - id: ruff

# TODO add pylint, flake8, mypy as pre-push hook?
