version: '3.8'

services:

  alerts_backend:
    build:
      context: .
      dockerfile: alerts_backend/dockerfiles/server.dockerfile
    container_name: alerts_backend
    volumes:
    - ./alerts_backend:/app
    - ./pubsub:/app/pubsub
    environment:
    - DJANGO_SETTINGS_MODULE=alerts_backend.settings_docker
    ports:
    - 8000:8000
    depends_on:
    - alerts_celery

  alerts_celery:
    build:
      context: .
      dockerfile: alerts_backend/dockerfiles/celery.dockerfile
    container_name: alerts_celery
    volumes:
    - ./alerts_backend:/app
    - ./pubsub:/app/pubsub
    environment:
    - DJANGO_SETTINGS_MODULE=alerts_backend.settings_docker
    depends_on:
    - alerts_redis
    - alerts_postgres
    - pubsub_redis

  alerts_redis:
    image: redis:7.0.11-alpine
    container_name: alerts_redis

  alerts_postgres:
    build:
      context: .
      dockerfile: alerts_backend/dockerfiles/postgres.dockerfile
    container_name: alerts_postgres
    env_file:
    - alerts_backend/dockerfiles/env/postgres.env

  alerts_frontend:
    build:
      context: .
      dockerfile: alerts_frontend/dockerfiles/frontend.dockerfile
    container_name: alerts_frontend
    volumes:
    - ./alerts_frontend:/app
    ports:
    - 3000:3000
    depends_on:
    - alerts_backend

  alerts_swagger_ui:
    image: swaggerapi/swagger-ui
    container_name: alerts_swagger_ui
    ports:
    - 8080:8080
    environment:
    - SWAGGER_JSON=/schema.yml
    volumes:
    - ./alerts_backend/schema.yml:/schema.yml
    depends_on:
    - alerts_backend

  analytics_celery:
    build:
      context: .
      dockerfile: analytics/dockerfiles/celery.dockerfile
    container_name: analytics_celery
    volumes:
    - ./analytics:/app
    - ./pubsub:/app/pubsub
    environment:
    - DJANGO_SETTINGS_MODULE=analytics.settings_docker
    depends_on:
    - analytics_redis
    - analytics_postgres
    - pubsub_redis

  analytics_redis:
    image: redis:7.0.11-alpine
    container_name: analytics_redis

  analytics_postgres:
    build:
      context: .
      dockerfile: analytics/dockerfiles/postgres.dockerfile
    container_name: analytics_postgres
    env_file:
    - analytics/dockerfiles/env/postgres.env

  pubsub_redis:
    image: redis:7.0.11-alpine
    container_name: pubsub_redis
