"""
Django settings for alerts_backend project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from .settings import *

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


SPECTACULAR_SETTINGS = {
    'TITLE': 'Ebay Alerts',
    'DESCRIPTION': 'APIs to perform CRUD operations for Alerts',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # OTHER SETTINGS
    'SERVERS': [{
        'url': 'http://localhost:8000/',
        'description': 'Local server'
    }],
}


ALLOWED_HOSTS = []
# For Swagger UI
CORS_ALLOWED_ORIGINS = [
    f"http://localhost:8080",
]


LOCALHOST = 'host.docker.internal'

# Email settings for Inbucket (Local)
# -----------------------------------
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp_server'  # LOCALHOST
EMAIL_PORT = '2500'
# TODO: Check if host user and password are required
EMAIL_HOST_USER = 'your@djangoapp.com'
EMAIL_HOST_PASSWORD = 'password'
EMAIL_USE_TLS = False
EMAIL_USE_SSL = False

# # Email settings for Mailtrap (Local)
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'sandbox.smtp.mailtrap.io'
# EMAIL_PORT = '2525'
# # TODO: Host user and password are provided in send_mail() function for mailtrap to work
# EMAIL_HOST_USER = 'be6c3e73d086a1'
# EMAIL_HOST_PASSWORD = 'e98802c26bf19d'
# EMAIL_USE_TLS = False
# EMAIL_USE_SSL = False

POSTGRES_HOST = LOCALHOST  # TODO: Change to <container name> when running in docker
POSTGRES_PORT = "5432"

REDIS_HOST = LOCALHOST  # TODO: Change to <container name> when running in docker
REDIS_PORT = "6379"

# Redis
REDIS_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}"
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
        "KEY_PREFIX": "DOC",
    }
}

# Celery
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "ebay_alert",
        "USER": "ebay_alert",
        "PASSWORD": "ebay_alert",
        "HOST": f"{POSTGRES_HOST}",
        "PORT": f"{POSTGRES_PORT}"
    }
}
