# Generated by Django 4.2.2 on 2023-07-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConsumedPubSubEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("alert-created", "ALERT_CREATED"),
                            ("alert-updated", "ALERT_UPDATED"),
                            ("alert-deleted", "ALERT_DELETED"),
                            ("new-products", "NEW_PRODUCTS"),
                        ],
                        max_length=255,
                    ),
                ),
                ("payload", models.JSONField()),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("processed", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductPriceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_id", models.CharField(db_index=True, max_length=255)),
                ("title", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(max_length=3)),
                ("timestamp", models.DateTimeField()),
                ("image_url", models.URLField(blank=True, max_length=2048, null=True)),
                ("web_url", models.URLField(blank=True, max_length=2048, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ActiveAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uid", models.IntegerField(db_index=True, unique=True)),
                ("email", models.EmailField(db_index=True, max_length=128)),
                ("keywords", models.TextField()),
                ("frequency", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tracked_products",
                    models.ManyToManyField(blank=True, to="insights.productpricelog"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
